import type { BuiltinSkill } from "./types";

// Harness-bundled skills are compiled into the TypeScript harness and synced
// into the same pointer/object-backed store as user-created skills. Add entries
// here when a skill should ship with the harness itself.
export const BUILTIN_SKILLS: BuiltinSkill[] = [
  {
    id: "apps",
    name: "Apps",
    content: "---\ndescription: >\n  Use when creating, registering, opening, implementing, or debugging harness UI apps.\n  Covers app manifests, bundles, handlers, RDF/memory indexes, chat-open facts,\n  runtime iframe APIs, state pointers, and app registration/opening APIs.\n---\n\n# Harness UI apps\n\nUse this skill when work involves harness UI apps in the right sidebar/apps view. This is about Moo harness UI apps, not general product or mobile/desktop app advice.\n\n## App model\n\n- Apps are harness UI apps surfaced in the right sidebar/apps view.\n- Valid app ids match `/^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,79}$/`.\n- Manifests use `{id,title,description?,icon?,entry?,api?}`.\n- Bundles use `{html?,css?,js?,files?}`.\n- The UI is firmly square; do not round corners unless explicitly asked.\n\n## Create/register apps\n\n- In `runTS`, prefer `moo.ui.apps.register({manifest,bundle,handler?})` to create/register apps.\n- Lower-level storage can use `moo.objects.putJSON({kind,value})` and `moo.objects.putText({kind,text})`.\n- App handler source runs as `async with (moo, request, context)`.\n- Handler request shape: `request={command,input,context}`.\n- Handler context shape: `context={uiId,chatId,instanceId}`.\n- Handlers return JSON-ish data and cannot import modules.\n\n## Index apps\n\nIndex app facts in user-wide memory with `moo.memory.assert({facts:[...]})`:\n\n- `ui:<id> rdf:type ui:App`\n- `ui:<id> ui:title <title>`\n- optional `ui:<id> ui:description <description>`\n- optional `ui:<id> ui:manifest <manifestHash>`\n- optional `ui:<id> ui:bundle <bundleHash>`\n- optional `ui:<id> ui:handler <handlerHash>`\n- `ui:<id> ui:updatedAt <datetime>`\n\n## Open apps in chat\n\nTo open an app in the current chat's right sidebar, call:\n\n- `await moo.ui.apps.open({chatId,uiId,instanceId?,state?})`\n\nThe helper records chat-scoped app facts, creates or reuses a UI instance, sets `pointer:uiinst/<instanceId>/state`, and broadcasts a live `ui-open` event so the web sidebar opens without a reload. Use manual facts only for diagnostics/backfills:\n\n- store `chat/<chatId>/facts`, graph `chat:<chatId>`\n- `chat:<id> ui:involves ui:<id>`\n- single current `chat:<id> ui:primary ui:<id>`\n- `uiinst:<instanceId> rdf:type ui:Instance`\n- `uiinst:<instanceId> ui:app ui:<id>`\n- `uiinst:<instanceId> ui:chat chat:<chatId>`\n- `uiinst:<instanceId> ui:statePointer pointer:uiinst/<instanceId>/state`\n\n## Runtime iframe API\n\nThe app iframe exposes `window.moo`:\n\n- `state.get()` / `state.set(value)`\n- `call(name,input)` to invoke the app handler\n- `open(uiId,instanceId?)` to open another app/instance\n- `memory.query(patterns, opts?)`\n- `memory.triples(pattern?)`\n- `memory.assert(...)`\n- `memory.retract(...)`\n- `memory.patch(...)`\n- `memory.project(project)`",
  },
];
